# Generated by Django 2.2.3 on 2019-09-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupsList',
            fields=[
                ('Group_Name', models.CharField(default='Group name', max_length=400, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Full_Name', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('School', models.CharField(max_length=400)),
                ('Subject', models.CharField(max_length=6)),
                ('Grade', models.IntegerField()),
                ('Email', models.EmailField(max_length=400)),
                ('Phone_Number', models.CharField(max_length=11)),
                ('Father_Number', models.CharField(max_length=11)),
                ('Mother_Number', models.CharField(max_length=11)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Info.GroupsList')),
            ],
        ),
    ]
