# Generated by Django 2.2.3 on 2019-08-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Subject', models.CharField(max_length=6)),
                ('Location', models.CharField(max_length=300)),
                ('Phone', models.CharField(max_length=11)),
            ],
        ),
    ]
